//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mondop.Templates.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mondop.Templates.Test.TestTemplates", typeof(TestTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@ name TestTemplateClassA @&gt;
        ///&lt;@ input Mondop.Templates.Test.Model.TestClassA, Mondop.Templates.Test as classA @&gt;
        ///Hello &lt;@#classA.Name@&gt;
        ///&lt;@ foreach(classB in classA.BClasses) @&gt;
        ///	&lt;@ br @&gt;Hello &lt;@#classB.Name@&gt;
        ///&lt;@ end @&gt;.
        /// </summary>
        internal static string TestEngineTemplate {
            get {
                return ResourceManager.GetString("TestEngineTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TestEngineTemplate_TestClassB {
            get {
                return ResourceManager.GetString("TestEngineTemplate_TestClassB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;@ name TestTemplate @&gt;
        ///&lt;@ input Mondop.CodeDom.CompileUnit as compileUnit @&gt;
        ///// Just some comment
        ///&lt;@foreach(ns in compileUnit.Namespaces)@&gt;
        ///	&lt;@call(ns)@&gt;
        ///&lt;@ end @&gt;.
        /// </summary>
        internal static string TestTemplate {
            get {
                return ResourceManager.GetString("TestTemplate", resourceCulture);
            }
        }
    }
}
